name: Deploy in main

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Supprimez la strat√©gie "matrix" inutile ici
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Remove npm lockfile to avoid mixing managers
        run: rm -f package-lock.json

      - name: Install dependencies with Yarn
        run: yarn install --non-interactive

      - name: Build project
        run: yarn build
        env:
          VITE_RAPIDAPI_KEY: ${{ secrets.VITE_RAPIDAPI_KEY }}
          VITE_RAPIDAPI_HOST: ${{ secrets.VITE_RAPIDAPI_HOST }}
          VITE_RAPIDAPI_BASE_URL: ${{ secrets.VITE_RAPIDAPI_BASE_URL }}

      - name: Install Wrangler globally
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler pages deploy dist --project-name=cyoutube
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_DEPLOY_TO_PAGES_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

        #   eZ5sTtI-62Ah7sTM69Us85_oExmzH7eRH4DGhAb7
